function one() {
    window.alert(
      "The Great Pyramid of Giza (also known as the Pyramid of Khufu or the Pyramid of Cheops) is the oldest and largest of the pyramids in the Giza pyramid complex bordering present-day Giza in Greater Cairo, Egypt. It is the oldest of the Seven Wonders of the Ancient World, and the only one to remain largely intact. Egyptologists conclude that the pyramid was built as a tomb for the Fourth Dynasty Egyptian pharaoh Khufu and estimate that it took up to 26 years to build and was completed circa 2560 BC. Initially standing at 146.5 metres (481 feet), the Great Pyramid was the tallest man-made structure in the world for more than 3,800 years. It is estimated to weigh approximately 6 million tonnes, and consists of 2.3 million blocks of limestone and granite, some weighing as much as 80 tonnes. It was originally covered by white limestone casing stones that formed a smooth outer surface; what is seen today is the underlying core structure, although a few casing stones can still be seen at the base. It was built by extracting huge stones from quarries and dragging them into place, but there are varying scientific and alternative theories about the exact construction technique. There are three known chambers inside the Great Pyramid. The lowest chamber was cut into the bedrock upon which the pyramid was built but remained unfinished. The so-called Queen's Chamber and King's Chamber are higher up, within the pyramid structure. The main part of the pyramid complex is a set of buildings that included two mortuary temples in honour of Khufu (one close to the pyramid and one near the Nile), three smaller pyramids for Khufu's wives, an even smaller satellite pyramid, a raised causeway connecting the two temples, and small mastaba tombs for nobles surrounding the pyramid."
    );
  }
  function two() {
    window.alert(
      "The Temple of Artemis or Artemision (Greek: Ἀρτεμίσιον; Turkish: Artemis Tapınağı), also known less precisely as the Temple of Diana, was a Greek temple dedicated to an ancient, local form of the goddess Artemis (associated with Diana, a Roman goddess). It was located in Ephesus (near the modern town of Selçuk in present-day Turkey). It was completely rebuilt twice, once after a devastating flood and three hundred years later after an act of arson, and in its final form was one of the Seven Wonders of the Ancient World. By 401 AD it had been ruined or destroyed. Only foundations and fragments of the last temple remain at the site. The earliest version of the temple (a temenos) antedated the Ionic immigration by many years, and dates to the Bronze Age. Callimachus, in his Hymn to Artemis, attributed it to the Amazons. In the 7th century BC, it was destroyed by a flood. Its reconstruction, in more grandiose form, began around 550 BC, under Chersiphron, the Cretan architect, and his son Metagenes. The project was funded by Croesus of Lydia, and took 10 years to complete. This version of the temple was destroyed in 356 BC by Herostratus in an act of arson. The next, greatest and last form of the temple, funded by the Ephesians themselves, is described in Antipater of Sidon's list of the world's Seven Wonders: I have set eyes on the wall of lofty Babylon on which is a road for chariots, and the statue of Zeus by the Alpheus, and the hanging gardens, and the colossus of the Sun, and the huge labour of the high pyramids, and the vast tomb of Mausolus; but when I saw the house of Artemis that mounted to the clouds, those other marvels lost their brilliancy, and I said, Lo, apart from Olympus, the Sun never looked on aught so grand."
    );
  }
  function three() {
    window.alert(
      "The Hanging Gardens of Babylon were one of the Seven Wonders of the Ancient World listed by Hellenic culture. They were described as a remarkable feat of engineering with an ascending series of tiered gardens containing a wide variety of trees, shrubs, and vines, resembling a large green mountain constructed of mud bricks. It was said to have been built in the ancient city of Babylon, near present-day Hillah, Babil province, in Iraq. The Hanging Gardens' name is derived from the Greek word kremastós (κρεμαστός, lit. 'overhanging'), which has a broader meaning than the modern English word hanging and refers to trees being planted on a raised structure such as a terrace. According to one legend, the Hanging Gardens were built alongside a grand palace known as The Marvel of Mankind, by the Neo-Babylonian King Nebuchadnezzar II (who ruled between 605 and 562 BC), for his Median wife Queen Amytis, because she missed the green hills and valleys of her homeland. This was attested to by the Babylonian priest Berossus, writing in about 290 BC, a description that was later quoted by Josephus. The construction of the Hanging Gardens has also been attributed to the legendary queen Semiramis, who supposedly ruled Babylon in the 9th century BC, and they have been called the Hanging Gardens of Semiramis as an alternative name. The Hanging Gardens are the only one of the Seven Wonders for which the location has not been definitively established. There are no extant Babylonian texts that mention the gardens, and no definitive archaeological evidence has been found in Babylon. Three theories have been suggested to account for this: firstly, that they were purely mythical, and the descriptions found in ancient Greek and Roman writings (including those of Strabo, Diodorus Siculus and Quintus Curtius Rufus) represented a romantic ideal of an eastern garden; secondly, that they existed in Babylon, but were completely destroyed sometime around the first century AD; and thirdly, that the lege…"
    );
  }
  function four() {
    window.alert(
      "The Lighthouse of Alexandria, sometimes called the Pharos of Alexandria , was a lighthouse built by the Ptolemaic Kingdom, during the reign of Ptolemy II Philadelphus (280–247 BC), which has been estimated to be at least 100 metres (330 ft) in overall height. One of the Seven Wonders of the Ancient World, for many centuries it was one of the tallest man-made structures in the world. The lighthouse was severely damaged by three earthquakes between 956 AD and 1323 and became an abandoned ruin. It was the third-longest surviving ancient wonder (after the Mausoleum at Halicarnassus and the extant Great Pyramid of Giza), surviving in part until 1480, when the last of its remnant stones were used to build the Citadel of Qaitbay on the site. In 1994, a team of French archaeologists dived into the water of Alexandria's Eastern Harbour and discovered some remains of the lighthouse on the sea floor. In 2016 the Ministry of State of Antiquities in Egypt had plans to turn submerged ruins of ancient Alexandria, including those of the Pharos, into an underwater museum."
    );
  }
  function five() {
    window.alert(
      "The Statue of Zeus at Olympia was a giant seated figure, about 12.4 m (41 ft) tall, made by the Greek sculptor Phidias around 435 BC at the sanctuary of Olympia, Greece, and erected in the Temple of Zeus there. Zeus was the sky and thunder god in ancient Greek religion, who ruled as king of the gods of Mount Olympus. The statue was a chryselephantine sculpture of ivory plates and gold panels on a wooden framework. Zeus sat on a painted cedarwood throne ornamented with ebony, ivory, gold and precious stones. It was one of the Seven Wonders of the Ancient World. The statue was lost and destroyed during the 5th century AD; details of its form are known only from ancient Greek descriptions and representations on coins."
    );
  }
  function six() {
    window.alert(
      "The Mausoleum at Halicarnassus or Tomb of Mausolus (Ancient Greek: Μαυσωλεῖον τῆς Ἁλικαρνασσοῦ; Turkish: Halikarnas Mozolesi) was a tomb built between 353 and 350 BC in Halicarnassus (present Bodrum, Turkey) for Mausolus, a native Anatolian from Caria and a satrap in the Achaemenid Empire, and his sister-wife Artemisia II of Caria. The structure was designed by the Greek architects Satyros and Pythius of Priene. Its elevated tomb structure is derived from the tombs of neighbouring Lycia, a territory Mausolus had invaded and annexed circa 360 BC, such as the Nereid Monument. The Mausoleum was approximately 45 m (148 ft) in height, and the four sides were adorned with sculptural reliefs, each created by one of four Greek sculptors: Leochares, Bryaxis, Scopas of Paros, and Timotheus. The mausoleum was considered to be such an aesthetic triumph that Antipater of Sidon identified it as one of his Seven Wonders of the Ancient World. It was destroyed by successive earthquakes from the 12th to the 15th century, the last surviving of the six destroyed wonders. The word mausoleum has now come to be used generically for an above-ground tomb."
    );
  }
  function seven() {
    window.alert(
      "The Colossus of Rhodes (Ancient Greek: ὁ Κολοσσὸς Ῥόδιος, romanized: ho Kolossòs Rhódios Greek: Κολοσσός της Ρόδου, romanized: Kolossós tes Rhódou) was a statue of the Greek sun-god Helios, erected in the city of Rhodes, on the Greek island of the same name, by Chares of Lindos in 280 BC. One of the Seven Wonders of the Ancient World, it was constructed to celebrate its successful defense against Demetrius Poliorcetes, who had besieged it for a year with a large army and navy. According to most contemporary descriptions, the Colossus stood approximately 70 cubits, or 33 metres (108 feet) high – approximately the height of the modern Statue of Liberty from feet to crown – making it the tallest statue in the ancient world. It collapsed during the earthquake of 226 BC, although parts of it were preserved. In accordance with a certain oracle, the Rhodians did not build it again. John Malalas wrote that Hadrian in his reign re-erected the Colossus, but he was wrong. According to Suda, the Rhodians were called Colossaeans (Κολοσσαεῖς), because they erected the statue on the island. Since 2008, a series of as-yet-unrealized proposals to build a new Colossus at Rhodes Harbour have been announced, although the actual location of the original monument remains in dispute."
    );
  }
  